export const itemlist = [
  {
    id: "1",
    img: "../../../mercedesA180.jpg",
    name: "MERCEDES A180 7G-TRONIC 2019 GOD A 180 REG.DO 11/24",
    category: "Mercedes",
    year: 2017,
    price: 45000,
    description:
      "Boja vozila: Crna, 3xSLine, S line Trokraki kožni multifunkcionalni volan sa F1 komandama, vrituelni sat, crno nebo, prednji i zadnji parking senzori sa vizuelnim prikazom, kamera za asistenciju pri parkiranju, 21'' felge sa zimskim gumama, Vazdusni ovjes, Active sound, Parking assist, Pola koza, pola alkantara profilisana SLINE sjedista, Električno podešavanje prednjih sjedista sa memorijom, Električno podešavanje lumbalne potpore na svim sjedištima, Navigacija, Ambijentalno osvjetljenje, Električno podešavanje volana po visini i dubini, Električno podešavanje retrovizora sa zaklapanjem, Grijanje prednjih i zadnjih sjedišta, 3 zone digitalna klima, Adaptivna FULL LED MATRIX svjetla sa fabrički integrisanim, LED dnevnim svjetlima, Elektricno otvaranje gepeka, Veliki board ekran, Start stop sistem, Distance control sistem za pracenje vozila ispred, Lane assist sistem za pracenje bijele linije, Senzor za automatska svjetla, Senzor za kišu, Samozatamnjivanje svih retrovizora, Bluetooth Telefon, SD card, CD Changer, Bluetooth Music, AUX, Kompletan zatamnjen lumar folijom, registrovano, Bh porijeklo, servisiran u ovlasten servisu..",
    logo: "../../mercedes.webp",
    fuel: "Diesel",
    model: "A180",
    mileage: 280000,
    transmision: "Automatic",
  },
  {
    id: "2",
    img: "../../../volvo.webp",
    category: "Volvo",
    name: "Volvo XC40",
    price: 69000,
    fuel: "Diesel",
    transmision: "Automatic",
  },
  {
    id: "3",
    img: "../../../bmw.webp",
    category: "BMW",
    name: "BMW G11",
    price: 85990,
    fuel: "Diesel",
    transmision: "Automatic",
  },
  {
    id: "4",
    img: "../../../porsche.webp",
    category: "Porsche",
    name: "PORSCHE MACAN II",
    price: 159000,
    fuel: "Petrol",
    transmision: "Automatic",
  },
  {
    id: "5",
    img: "../../../passat.webp",
    category: "Volkswagen",
    name: "Passat B8",
    price: 48900,
    fuel: "Diesel",
    transmision: "Automatic",
  },
  {
    id: "6",
    img: "../../../skoda.webp",
    category: "Škoda",
    name: "Škoda Kodiaq",
    price: 20450,
    fuel: "Diesel",
    transmision: "Automatic",
  },
  {
    id: "7",
    img: "../../../bmwm8.webp",
    category: "BMW",
    name: "BMW M8 COUPE ",
    price: 270000,
    fuel: "Petrol",
    transmision: "Automatic",
  },
  {
    id: "8",
    img: "../../../audirs5.webp",
    category: "AUDI",
    name: "AUDI RS5 ",
    price: 45000,
    fuel: "Petrol",
    transmision: "Automatic",
  },
  {
    id: "9",
    img: "../../../touareg.webp",
    category: "Volkswagen",
    name: "Volkswagen Touareg",
    price: 88000,
    fuel: "Diesel",
    transmision: "Automatic",
  },
  {
    id: "10",
    img: "../../../ford.webp",
    category: "Ford",
    name: "Ford F150 PICK UP",
    price: 22000,
    fuel: "Petrol",
    transmision: "Automatic",
  },
  {
    id: "11",
    img: "../../../mbenz.webp",
    category: "Mercedes",
    name: "Mercedes-Benz S 400d ",
    price: 99000,
    fuel: "Diesel",
    transmision: "Automatic",
  },
  {
    id: "12",
    img: "../../../golf7.webp",
    category: "Volkswagen",
    name: "VW GOLF VII 7",
    price: 10000,
    fuel: "Petrol",
    transmision: "Automatic",
  },
];
